language: java
dist: trusty
jdk:
  #- openjdk8
  - openjdk11
env:
  - CODACY_PROJECT_TOKEN=9001
script: ./gradlew check
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- bash <(curl -Ls https://coverage.codacy.com/get.sh)
